name: PR Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests with coverage
        id: run-tests
        run: npm test -- --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        if: always()
        with:
          webhook-url: ${{ secrets.DISCORD }}
          content: |
            **PR 테스트 결과**
            Repository: ${{ github.repository }}
            Branch: ${{ github.head_ref }}
            Commit: [${{ github.sha }}](${{ github.event.pull_request.html_url }})
            Author: ${{ github.actor }}
            
            Status: ${{ job.status == 'success' && '✅ 성공' || '❌ 실패' }}
            
            [Actions에서 자세히 보기](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            [Codecov에서 커버리지 확인](https://codecov.io/gh/${{ github.repository }})
